# Generated by generate.py
import struct
import colorsys
from typing import Self


class FieldBase:
    def _get_string(self, raw):
        return raw.split(b'\x00')[0].decode()

    def make_packet(self):
        code = self.__class__.CODE
        if hasattr(self, 'fieldcode'):
            code = self.fieldcode

        header = struct.pack('!H2x 4s', len(self.raw) + 8, code.encode())
        return header + self.raw

    def serialize(self):
        return None

    @classmethod
    def restore(cls, data, instance_override=None):
        return


class PreviewBusInputField(FieldBase):
    """
    Data from the `PrvI` field. This represents the active channel on the preview bus of the specific M/E unit.

    The mixer will send a field for every M/E unit in the mixer.

    ====== ==== ====== ===========
    Offset Size Type   Description
    ====== ==== ====== ===========
    0      1    u8     M/E Index
    1      1    ?      padding
    2      2    u16    Source index
    4      1    bool   Preview is mixed in program during a transition
    5      3    ?      padding
    ====== ==== ====== ===========

    After parsing:

    :ivar index: M/E Index
    :ivar source: Source index
    :ivar in_program: Preview is mixed in program during a transition
    """

    CODE = "PrvI"
    STRUCT = struct.Struct('>BxH ?3x')

    def __init__(self, raw: bytes):
        """
        :param raw: Bytes containing the field contents
        """
        self.raw = raw
        field = self.STRUCT.unpack(raw)
        self.index = field[0]
        self.source = field[1]
        self.in_program = field[2]

    @classmethod
    def create(cls, source: int, index: int = 0, in_program: bool = False) -> Self:
        """
        :param index: M/E Index, defaults to 0
        :param source: Source index
        :param in_program: Preview is mixed in program during a transition, defaults to False
        :return: Instance of PreviewBusInputField with the data applied
        """
        raw = cls.STRUCT.pack(source, index, in_program)
        return cls(raw)

    def uncreate(self) -> tuple:
        """Create arguments to feed into PreviewBusInputField.create()"""
        return self.source, self.index, self.in_program

    def __repr__(self):
        return f"<preview-bus-input index={self.index} source={self.source}>"


class FadeToBlackStateField(FieldBase):
    """
    Data from the `FtbS`. This contains the information about the fade-to-black transition.

    ====== ==== ====== ===========
    Offset Size Type   Description
    ====== ==== ====== ===========
    0      1    u8     M/E Index
    1      1    bool   Fade to black done (blinking in control panel)
    2      1    bool   Fade to black is doing fade transition (solid red in control panel)
    3      1    u8     Frames remaining in the fade transition
    ====== ==== ====== ===========

    After parsing:

    :ivar index: M/E Index
    :ivar done: Fade to black done (blinking in control panel)
    :ivar transitioning: Fade to black is doing fade transition (solid red in control panel)
    :ivar frames_remaining: Frames remaining in the fade transition
    """

    CODE = "PrgI"
    STRUCT = struct.Struct('>B??B')

    def __init__(self, raw: bytes):
        """
        :param raw: Bytes containing the field contents
        """
        self.raw = raw
        field = self.STRUCT.unpack(raw)
        self.index = field[0]
        self.done = field[1]
        self.transitioning = field[2]
        self.frames_remaining = field[3]

    @classmethod
    def create(cls, done: bool, transitioning: bool, frames_remaining: int, index: int = 0) -> Self:
        """
        :param index: M/E Index, defaults to 0
        :param done: Fade to black done (blinking in control panel)
        :param transitioning: Fade to black is doing fade transition (solid red in control panel)
        :param frames_remaining: Frames remaining in the fade transition
        :return: Instance of FadeToBlackStateField with the data applied
        """
        raw = cls.STRUCT.pack(done, transitioning, frames_remaining, index)
        return cls(raw)

    def uncreate(self) -> tuple:
        """Create arguments to feed into FadeToBlackStateField.create()"""
        return self.done, self.transitioning, self.frames_remaining, self.index

    def __repr__(self):
        return f"<fade-to-black-state index={self.index} transitioning={self.transitioning} frames_remaining={self.frames_remaining}>"


class ProgramBusInputField(FieldBase):
    """
    Data from the `PrgI` field. This represents the active channel on the program bus of the specific M/E unit.

    The mixer will send a field for every M/E unit in the mixer.

    ====== ==== ====== ===========
    Offset Size Type   Description
    ====== ==== ====== ===========
    0      1    u8     M/E Index
    1      1    ?      padding
    2      2    u16    Source index
    ====== ==== ====== ===========

    After parsing:

    :ivar index: M/E Index
    :ivar source: Source index
    """

    CODE = "PrgI"
    STRUCT = struct.Struct('>BxH')

    def __init__(self, raw: bytes):
        """
        :param raw: Bytes containing the field contents
        """
        self.raw = raw
        field = self.STRUCT.unpack(raw)
        self.index = field[0]
        self.source = field[1]

    @classmethod
    def create(cls, source: int, index: int = 0) -> Self:
        """
        :param index: M/E Index, defaults to 0
        :param source: Source index
        :return: Instance of ProgramBusInputField with the data applied
        """
        raw = cls.STRUCT.pack(source, index)
        return cls(raw)

    def uncreate(self) -> tuple:
        """Create arguments to feed into ProgramBusInputField.create()"""
        return self.source, self.index

    def __repr__(self):
        return f"<program-bus-input index={self.index} source={self.source}>"


class TallySourceField(FieldBase):
    """
    Data from the `TlSr`. This is the status of the tally light for every input, but indexed on source index

    ====== ==== ====== ===========
    Offset Size Type   Description
    ====== ==== ====== ===========
    0      2    u16    Total number of tally lights
    ====== ==== ====== ===========

    Followed by this repeated block:

    ====== ==== ====== ===========
    Offset Size Type   Description
    ====== ==== ====== ===========
    0      2    u16    Source index
    0      1    u8     Tally bitfield
    ====== ==== ====== ===========

    After parsing:

    :ivar num: Total number of tally lights
    """

    CODE = "TlSr"
    STRUCT = struct.Struct('>H')
    REPEATED = struct.Struct('>HB')

    def __init__(self, raw: bytes):
        """
        :param raw: Bytes containing the field contents
        """
        self.raw = raw
        field = self.STRUCT.unpack(raw)
        self.num = field[0]
        self.tally = {}
        for i in range(self.num):
            rf = self.REPEATED.unpack_from(raw, self.STRUCT.size + (i * self.REPEATED.size))
            self.tally[rf[0]] = (rf[1] & (1 << 0) != 0, rf[1] & (1 << 1) != 0, )

    @classmethod
    def create(cls, num: int) -> Self:
        """
        :param num: Total number of tally lights
        :return: Instance of TallySourceField with the data applied
        """
        raw = cls.STRUCT.pack(num)
        return cls(raw)

    def uncreate(self) -> tuple:
        """Create arguments to feed into TallySourceField.create()"""
        return self.num,

    def __repr__(self):
        return f"<tally-source num={self.num}>"


class ColorGeneratorField(FieldBase):
    """
    Data from the `ColV`. This is color set in the color generators of the mixer

    ====== ==== ====== ===========
    Offset Size Type   Description
    ====== ==== ====== ===========
    0      1    u8     Color generator index
    1      1    ?      padding
    2      2    u16    Hue, [0-3599]
    4      2    u16    Saturation, [0-1000]
    6      2    u16    Luma, [0-1000]
    ====== ==== ====== ===========

    After parsing:

    :ivar index: Color generator index
    :ivar hue: Hue, [0-3599]
    :ivar saturation: Saturation, [0-1000]
    :ivar luma: Luma, [0-1000]
    """

    CODE = "ColV"
    STRUCT = struct.Struct('>BxH HH')

    def __init__(self, raw: bytes):
        """
        :param raw: Bytes containing the field contents
        """
        self.raw = raw
        field = self.STRUCT.unpack(raw)
        self.index = field[0]
        self.hue = field[1] / 10.0
        self.saturation = field[2] / 1000.0
        self.luma = field[3] / 1000.0


    @classmethod
    def create(cls, hue: int, saturation: int, luma: int, index: int = 0) -> Self:
        """
        :param index: Color generator index, defaults to 0
        :param hue: Hue, [0-3599]
        :param saturation: Saturation, [0-1000]
        :param luma: Luma, [0-1000]
        :return: Instance of ColorGeneratorField with the data applied
        """
        raw = cls.STRUCT.pack(hue, saturation, luma, index)
        return cls(raw)

    def uncreate(self) -> tuple:
        """Create arguments to feed into ColorGeneratorField.create()"""
        return self.hue, self.saturation, self.luma, self.index

    def serialize(self) -> dict:
        """Create dict with the contents of this field for ColorGeneratorField.restore()"""
        return {
            "index": self.index,
            "hue": self.hue,
            "saturation": self.saturation,
            "luma": self.luma,
        }

    def instance_id(self) -> tuple:
        """Generate a tuple that uniquely identifies this instance on the hardware"""
        return (self.index, )

    @classmethod
    def restore(cls, data: dict, instance_override=None):
        """Generate commands to restore the state for this ColorGeneratorField based on the supplied data."""
        if instance_override is not None:
            data["index"] = instance_override[0]
        from pyatem.command import ColorGeneratorCommand
        return [
            ColorGeneratorCommand(index=data["index"], hue=data["hue"], saturation=data["saturation"], luma=data["luma"]),
        ]

    def get_rgb(self):
        """Get the color as RGB tuple (0.0-1.0)"""
        return colorsys.hls_to_rgb(self.hue / 360.0, self.luma, self.saturation)

    def __repr__(self):
        return f"<color-generator index={self.index} hue={self.hue} saturation={self.saturation} luma={self.luma}>"


class TallyIndexField(FieldBase):
    """
    Data from the `TlIn`. This is the status of the tally light for every input in order of index number.

    ====== ==== ====== ===========
    Offset Size Type   Description
    ====== ==== ====== ===========
    0      2    u16    Total number of tally lights
    ====== ==== ====== ===========

    Followed by this repeated block:

    ====== ==== ====== ===========
    Offset Size Type   Description
    ====== ==== ====== ===========
    0      1    u8     Tally bitfield
    ====== ==== ====== ===========

    After parsing:

    :ivar num: Total number of tally lights
    """

    CODE = "TlIn"
    STRUCT = struct.Struct('>H')
    REPEATED = struct.Struct('>B')

    def __init__(self, raw: bytes):
        """
        :param raw: Bytes containing the field contents
        """
        self.raw = raw
        field = self.STRUCT.unpack(raw)
        self.num = field[0]
        self.tally = []
        for i in range(self.num):
            rf = self.REPEATED.unpack_from(raw, self.STRUCT.size + (i * self.REPEATED.size))
            self.tally.append((rf[0] & (1 << 0) != 0, rf[0] & (1 << 1) != 0, ))

    @classmethod
    def create(cls, num: int) -> Self:
        """
        :param num: Total number of tally lights
        :return: Instance of TallyIndexField with the data applied
        """
        raw = cls.STRUCT.pack(num)
        return cls(raw)

    def uncreate(self) -> tuple:
        """Create arguments to feed into TallyIndexField.create()"""
        return self.num,

    def __repr__(self):
        return f"<tally-index num={self.num}>"


class TransitionSettingsField(FieldBase):
    """
    Data from the `TrSS` field. This stores the config of the "Next transition" and "Transition style" blocks on the control
    panels.

    The mixer will send a field for every M/E unit in the mixer.

    There are two sets of style/layer settings. The first set is the active transition settings. The second one will store
    the transitions settings if you change any of them while a transition is active. These settings will be applied as soon
    as the transition ends. This is signified by blinking transition settings buttons in the official control panels.

    ====== ==== ====== ===========
    Offset Size Type   Description
    ====== ==== ====== ===========
    0      1    u8     M/E Index
    1      1    u8     Transition style
    2      1    u8     Next transition layers
    3      1    u8     Next transition style
    4      1    u8     Next transition next transition layers
    ====== ==== ====== ===========

    The `Transition style` is an enum of these values:

    === ================
    Key Transition style
    === ================
    0   Mix
    1   Dip
    2   Wipe
    3   DVE
    4   Sting
    === ================

    After parsing:

    :ivar index: M/E Index
    :ivar style: Transition style
    :ivar nt: Next transition layers
    :ivar style_next: Next transition style
    :ivar ntn: Next transition next transition layers
    """

    CODE = "TrSS"
    STRUCT = struct.Struct('>BBBB B')

    STYLE_MIX = 0
    STYLE_DIP = 1
    STYLE_WIPE = 2
    STYLE_DVE = 3
    STYLE_STING = 4

    def __init__(self, raw: bytes):
        """
        :param raw: Bytes containing the field contents
        """
        self.raw = raw
        field = self.STRUCT.unpack(raw)
        self.index = field[0]
        self.style = field[1]
        self.next_transition_bkgd = field[2] & (1 << 0) != 0
        self.next_transition_key1 = field[2] & (1 << 1) != 0
        self.next_transition_key2 = field[2] & (1 << 2) != 0
        self.next_transition_key3 = field[2] & (1 << 3) != 0
        self.next_transition_key4 = field[2] & (1 << 4) != 0
        self.style_next = field[3]
        self.next_transition_bkgd_next = field[4] & (1 << 0) != 0
        self.next_transition_key1_next = field[4] & (1 << 1) != 0
        self.next_transition_key2_next = field[4] & (1 << 2) != 0
        self.next_transition_key3_next = field[4] & (1 << 3) != 0
        self.next_transition_key4_next = field[4] & (1 << 4) != 0

    @classmethod
    def create(cls, style: int, nt: int, style_next: int, ntn: int, index: int = 0) -> Self:
        """
        :param index: M/E Index, defaults to 0
        :param style: Transition style
        :param nt: Next transition layers
        :param style_next: Next transition style
        :param ntn: Next transition next transition layers
        :return: Instance of TransitionSettingsField with the data applied
        """
        raw = cls.STRUCT.pack(style, nt, style_next, ntn, index)
        return cls(raw)

    def uncreate(self) -> tuple:
        """Create arguments to feed into TransitionSettingsField.create()"""
        return self.style, self.nt, self.style_next, self.ntn, self.index

    def __repr__(self):
        return f"<transition-settings index={self.index} style={self.style}>"


class KeyOnAirField(FieldBase):
    """
    Data from the `KeOn`. This is the on-air state of the upstream keyers

    ====== ==== ====== ===========
    Offset Size Type   Description
    ====== ==== ====== ===========
    0      1    u8     M/E Index
    1      1    u8     Upstream keyer index
    2      1    bool   On-air
    3      1    ?      padding
    ====== ==== ====== ===========

    After parsing:

    :ivar index: M/E Index
    :ivar keyer: Upstream keyer index
    :ivar enabled: On-air
    """

    CODE = "KeOn"
    STRUCT = struct.Struct('>BB?x')

    def __init__(self, raw: bytes):
        """
        :param raw: Bytes containing the field contents
        """
        self.raw = raw
        field = self.STRUCT.unpack(raw)
        self.index = field[0]
        self.keyer = field[1]
        self.enabled = field[2]

    @classmethod
    def create(cls, keyer: int, enabled: bool, index: int = 0) -> Self:
        """
        :param index: M/E Index, defaults to 0
        :param keyer: Upstream keyer index
        :param enabled: On-air
        :return: Instance of KeyOnAirField with the data applied
        """
        raw = cls.STRUCT.pack(keyer, enabled, index)
        return cls(raw)

    def uncreate(self) -> tuple:
        """Create arguments to feed into KeyOnAirField.create()"""
        return self.keyer, self.enabled, self.index

    def __repr__(self):
        return f"<key-on-air index={self.index} keyer={self.keyer} enabled={self.enabled}>"


class TransitionPreviewField(FieldBase):
    """
    Data from the `TsPr` field. This represents the state of the "PREV TRANS" button on the mixer.

    The mixer will send a field for every M/E unit in the mixer.

    ====== ==== ====== ===========
    Offset Size Type   Description
    ====== ==== ====== ===========
    0      1    u8     M/E Index
    1      1    bool   Transition preview is enabled
    2      2    ?      padding
    ====== ==== ====== ===========

    After parsing:

    :ivar index: M/E Index
    :ivar enabled: Transition preview is enabled
    """

    CODE = "TsPr"
    STRUCT = struct.Struct('>B?2x')

    def __init__(self, raw: bytes):
        """
        :param raw: Bytes containing the field contents
        """
        self.raw = raw
        field = self.STRUCT.unpack(raw)
        self.index = field[0]
        self.enabled = field[1]

    @classmethod
    def create(cls, enabled: bool, index: int = 0) -> Self:
        """
        :param index: M/E Index, defaults to 0
        :param enabled: Transition preview is enabled
        :return: Instance of TransitionPreviewField with the data applied
        """
        raw = cls.STRUCT.pack(enabled, index)
        return cls(raw)

    def uncreate(self) -> tuple:
        """Create arguments to feed into TransitionPreviewField.create()"""
        return self.enabled, self.index

    def __repr__(self):
        return f"<transition-preview index={self.index} enabled={self.enabled}>"


class MediaplayerFileInfoField(FieldBase):
    """
    Data from the `MPfe`. This is the metadata about a single frame slot in the mediaplayer

    ====== ==== ====== ===========
    Offset Size Type   Description
    ====== ==== ====== ===========
    0      1    u8     Type
    1      1    ?      padding
    2      2    u16    Slot index
    4      1    bool   Slot is used
    5      16   bytes  The MD5 hash of the file in the slot
    21     2    ?      padding
    23     1    u8     Name of the slot, first byte is the number of characters
    ====== ==== ====== ===========

    The `Type` is an enum of these values:

    === ====
    Key Type
    === ====
    0   Still
    === ====

    After parsing:

    :ivar type: Type
    :ivar index: Slot index
    :ivar is_used: Slot is used
    :ivar hash: The MD5 hash of the file in the slot
    :ivar name_len: Name of the slot, first byte is the number of characters
    """

    CODE = "MPfe"
    STRUCT = struct.Struct('>BxH ?16s2xB')

    def __init__(self, raw: bytes):
        """
        :param raw: Bytes containing the field contents
        """
        self.raw = raw
        field = self.STRUCT.unpack(raw)
        self.type = field[0]
        self.index = field[1]
        self.is_used = field[2]
        self.hash = field[3]
        self.name_len = field[4]
        self.name = raw[self.STRUCT.size + self.name_len]

    @classmethod
    def create(cls, type: int, index: int, is_used: bool, hash: bytes, name_len: int) -> Self:
        """
        :param type: Type
        :param index: Slot index
        :param is_used: Slot is used
        :param hash: The MD5 hash of the file in the slot
        :param name_len: Name of the slot, first byte is the number of characters
        :return: Instance of MediaplayerFileInfoField with the data applied
        """
        raw = cls.STRUCT.pack(type, index, is_used, hash, name_len)
        return cls(raw)

    def uncreate(self) -> tuple:
        """Create arguments to feed into MediaplayerFileInfoField.create()"""
        return self.type, self.index, self.is_used, self.hash, self.name_len

    def __repr__(self):
        return f"<mediaplayer-file-info type={self.type} index={self.index}>"


class TransitionPositionField(FieldBase):
    """
    Data from the `TrPs` field. This represents the state of the transition T-handle position

    The mixer will send a field for every M/E unit in the mixer.

    ====== ==== ====== ===========
    Offset Size Type   Description
    ====== ==== ====== ===========
    0      1    u8     M/E Index
    1      1    bool   In transition
    2      1    u8     Number of frames left to complete the transition on auto
    3      1    ?      padding
    4      2    u16    Position of the transition, [0-9999]
    6      2    ?      padding
    ====== ==== ====== ===========

    After parsing:

    :ivar index: M/E Index
    :ivar in_transition: In transition
    :ivar frames_remaining: Number of frames left to complete the transition on auto
    :ivar position: Position of the transition, [0-9999]
    """

    CODE = "TrPs"
    STRUCT = struct.Struct('>B?Bx H2x')

    def __init__(self, raw: bytes):
        """
        :param raw: Bytes containing the field contents
        """
        self.raw = raw
        field = self.STRUCT.unpack(raw)
        self.index = field[0]
        self.in_transition = field[1]
        self.frames_remaining = field[2]
        self.position = field[3]

    @classmethod
    def create(cls, in_transition: bool, frames_remaining: int, position: int, index: int = 0) -> Self:
        """
        :param index: M/E Index, defaults to 0
        :param in_transition: In transition
        :param frames_remaining: Number of frames left to complete the transition on auto
        :param position: Position of the transition, [0-9999]
        :return: Instance of TransitionPositionField with the data applied
        """
        raw = cls.STRUCT.pack(in_transition, frames_remaining, position, index)
        return cls(raw)

    def uncreate(self) -> tuple:
        """Create arguments to feed into TransitionPositionField.create()"""
        return self.in_transition, self.frames_remaining, self.position, self.index

    def __repr__(self):
        return f"<transition-position index={self.index} in_transition={self.in_transition}>"


class TopologyField(FieldBase):
    """
    Data from the `_top` field. This describes the internal video routing topology.

    =================== ========= ======= ====== spec                Atem Mini 1M/E 4k TVS HD =================== =========
    ======= ====== M/E units           1         1       1 upstream keyers     1         1       1 downstream keyers   1
    2       2 dve                 1         1       1 stinger             0         1       0 supersources        0
    0       0 multiview           0         1       1 rs485               0         1       1 =================== =========
    ======= ======

    ====== ==== ====== ===========
    Offset Size Type   Description
    ====== ==== ====== ===========
    0      1    u8     Number of Mix/Effect units
    1      1    u8     Total number of sources
    2      1    u8     Number of downstream keyers
    3      1    u8     Number of AUX outputs
    4      1    u8     Number of Mix Minus outputs
    5      1    u8     Number of media players
    6      1    u8     Number of multiview generators
    7      1    u8     Number of RS485 connectors
    8      1    u8     Number of possible hyperdeck connections
    9      1    u8     Number of DVE units that are assignable
    10     1    u8     Number of stinger generators
    11     1    u8     Number of supersource generators
    12     1    bool   The multiviewer is routable
    13     1    u8     Number of talkback channels
    14     1    ?      unknown
    15     1    ?      unknown
    16     1    ?      unknown
    17     1    ?      unknown
    18     1    bool   Supports camera control
    19     1    ?      unknown
    20     1    ?      unknown
    21     1    ?      unknown
    22     1    bool   Use the new advanced chroma keyers
    23     1    bool   The hardware has no fixed function outputs, only AUX busses
    24     1    ?      unknown
    25     1    ?      unknown
    26     1    ?      unknown
    27     1    ?      unknown
    ====== ==== ====== ===========

    After parsing:

    :ivar me_units: Number of Mix/Effect units
    :ivar sources: Total number of sources
    :ivar downstream_keyers: Number of downstream keyers
    :ivar aux_busses: Number of AUX outputs
    :ivar mixminus_outputs: Number of Mix Minus outputs
    :ivar mediaplayers: Number of media players
    :ivar multiviewers: Number of multiview generators
    :ivar rs485: Number of RS485 connectors
    :ivar hyperdecks: Number of possible hyperdeck connections
    :ivar dve: Number of DVE units that are assignable
    :ivar stingers: Number of stinger generators
    :ivar supersources: Number of supersource generators
    :ivar multiviewer_routable: The multiviewer is routable
    :ivar talkback_channels: Number of talkback channels
    :ivar camera_control: Supports camera control
    :ivar advanced_chroma_keyers: Use the new advanced chroma keyers
    :ivar only_configurable_outputs: The hardware has no fixed function outputs, only AUX busses
    """

    CODE = "_top"
    STRUCT = struct.Struct('>BBBB BBBB BBBB ?Bxx xx?x xx?? xxxx')

    def __init__(self, raw: bytes):
        """
        :param raw: Bytes containing the field contents
        """
        self.raw = raw
        field = self.STRUCT.unpack(raw)
        self.me_units = field[0]
        self.sources = field[1]
        self.downstream_keyers = field[2]
        self.aux_busses = field[3]
        self.mixminus_outputs = field[4]
        self.mediaplayers = field[5]
        self.multiviewers = field[6]
        self.rs485 = field[7]
        self.hyperdecks = field[8]
        self.dve = field[9]
        self.stingers = field[10]
        self.supersources = field[11]
        self.multiviewer_routable = field[12]
        self.talkback_channels = field[13]
        self.camera_control = field[14]
        self.advanced_chroma_keyers = field[15]
        self.only_configurable_outputs = field[16]

    @classmethod
    def create(cls, me_units: int, sources: int, downstream_keyers: int, aux_busses: int, mixminus_outputs: int, mediaplayers: int, multiviewers: int, rs485: int, hyperdecks: int, dve: int, stingers: int, supersources: int, multiviewer_routable: bool, talkback_channels: int, camera_control: bool, advanced_chroma_keyers: bool, only_configurable_outputs: bool) -> Self:
        """
        :param me_units: Number of Mix/Effect units
        :param sources: Total number of sources
        :param downstream_keyers: Number of downstream keyers
        :param aux_busses: Number of AUX outputs
        :param mixminus_outputs: Number of Mix Minus outputs
        :param mediaplayers: Number of media players
        :param multiviewers: Number of multiview generators
        :param rs485: Number of RS485 connectors
        :param hyperdecks: Number of possible hyperdeck connections
        :param dve: Number of DVE units that are assignable
        :param stingers: Number of stinger generators
        :param supersources: Number of supersource generators
        :param multiviewer_routable: The multiviewer is routable
        :param talkback_channels: Number of talkback channels
        :param camera_control: Supports camera control
        :param advanced_chroma_keyers: Use the new advanced chroma keyers
        :param only_configurable_outputs: The hardware has no fixed function outputs, only AUX busses
        :return: Instance of TopologyField with the data applied
        """
        raw = cls.STRUCT.pack(me_units, sources, downstream_keyers, aux_busses, mixminus_outputs, mediaplayers,
            multiviewers, rs485, hyperdecks, dve, stingers, supersources, multiviewer_routable, talkback_channels,
            camera_control, advanced_chroma_keyers, only_configurable_outputs)
        return cls(raw)

    def uncreate(self) -> tuple:
        """Create arguments to feed into TopologyField.create()"""
        return self.me_units, self.sources, self.downstream_keyers, self.aux_busses, self.mixminus_outputs, self.mediaplayers, self.multiviewers, self.rs485, self.hyperdecks, self.dve, self.stingers, self.supersources, self.multiviewer_routable, self.talkback_channels, self.camera_control, self.advanced_chroma_keyers, self.only_configurable_outputs

    def __repr__(self):
        return f"<topology me_units={self.me_units} sources={self.sources}>"


class AuxOutputSourceField(FieldBase):
    """
    Data from the `AuxS`. The routing for the AUX outputs of the hardware.

    ====== ==== ====== ===========
    Offset Size Type   Description
    ====== ==== ====== ===========
    0      1    u8     Aux output index
    1      1    ?      padding
    2      2    u16    Source index
    ====== ==== ====== ===========

    After parsing:

    :ivar index: Aux output index
    :ivar source: Source index
    """

    CODE = "AuxS"
    STRUCT = struct.Struct('>BxH')

    def __init__(self, raw: bytes):
        """
        :param raw: Bytes containing the field contents
        """
        self.raw = raw
        field = self.STRUCT.unpack(raw)
        self.index = field[0]
        self.source = field[1]

    @classmethod
    def create(cls, index: int, source: int) -> Self:
        """
        :param index: Aux output index
        :param source: Source index
        :return: Instance of AuxOutputSourceField with the data applied
        """
        raw = cls.STRUCT.pack(index, source)
        return cls(raw)

    def uncreate(self) -> tuple:
        """Create arguments to feed into AuxOutputSourceField.create()"""
        return self.index, self.source

    def __repr__(self):
        return f"<aux-output-source index={self.index} source={self.source}>"


class MediaplayerSlotsField(FieldBase):
    """
    Data from the `_mpl` field. This stores basic info about the mediaplayer slots.

    ====== ==== ====== ===========
    Offset Size Type   Description
    ====== ==== ====== ===========
    0      1    u8     Number of still slots
    1      1    u8     Number of clip slots
    2      2    ?      padding
    ====== ==== ====== ===========

    After parsing:

    :ivar stills: Number of still slots
    :ivar clips: Number of clip slots
    """

    CODE = "_mpl"
    STRUCT = struct.Struct('>BB2x')

    def __init__(self, raw: bytes):
        """
        :param raw: Bytes containing the field contents
        """
        self.raw = raw
        field = self.STRUCT.unpack(raw)
        self.stills = field[0]
        self.clips = field[1]

    @classmethod
    def create(cls, stills: int, clips: int) -> Self:
        """
        :param stills: Number of still slots
        :param clips: Number of clip slots
        :return: Instance of MediaplayerSlotsField with the data applied
        """
        raw = cls.STRUCT.pack(stills, clips)
        return cls(raw)

    def uncreate(self) -> tuple:
        """Create arguments to feed into MediaplayerSlotsField.create()"""
        return self.stills, self.clips

    def __repr__(self):
        return f"<mediaplayer-slots stills={self.stills} clips={self.clips}>"


class TimeConfigField(FieldBase):
    """
    Data from the `TCCc` field. This contains the freerun/time of day setting for the timecode mode.

    ====== ==== ====== ===========
    Offset Size Type   Description
    ====== ==== ====== ===========
    0      1    u8     Timecode mode
    1      3    ?      padding
    ====== ==== ====== ===========

    The `Timecode mode` is an enum of these values:

    === =============
    Key Timecode mode
    === =============
    0   Free-running timecode
    1   Time of day
    === =============

    After parsing:

    :ivar mode: Timecode mode
    """

    CODE = "TCCc"
    STRUCT = struct.Struct('>B3x')

    def __init__(self, raw: bytes):
        """
        :param raw: Bytes containing the field contents
        """
        self.raw = raw
        field = self.STRUCT.unpack(raw)
        self.mode = field[0]

    @classmethod
    def create(cls, mode: int = 0) -> Self:
        """
        :param mode: Timecode mode, defaults to 0
        :return: Instance of TimeConfigField with the data applied
        """
        raw = cls.STRUCT.pack(mode)
        return cls(raw)

    def uncreate(self) -> tuple:
        """Create arguments to feed into TimeConfigField.create()"""
        return self.mode,

    def __repr__(self):
        return f"<time-config mode={self.mode}>"


class TimeField(FieldBase):
    """
    Data from the `Time` field. This contains the value of the internal clock of the hardware.

    ====== ==== ====== ===========
    Offset Size Type   Description
    ====== ==== ====== ===========
    0      1    u8     Hours
    1      1    u8     Minutes
    2      1    u8     Seconds
    3      1    u8     Frames
    4      1    bool   Current mode uses dropframes
    5      3    ?      padding
    ====== ==== ====== ===========

    After parsing:

    :ivar hours: Hours
    :ivar minutes: Minutes
    :ivar seconds: Seconds
    :ivar frames: Frames
    :ivar is_dropframe: Current mode uses dropframes
    """

    CODE = "Time"
    STRUCT = struct.Struct('>BBBB ?3x')

    def __init__(self, raw: bytes):
        """
        :param raw: Bytes containing the field contents
        """
        self.raw = raw
        field = self.STRUCT.unpack(raw)
        self.hours = field[0]
        self.minutes = field[1]
        self.seconds = field[2]
        self.frames = field[3]
        self.is_dropframe = field[4]


    @classmethod
    def create(cls, hours: int = 0, minutes: int = 0, seconds: int = 0, frames: int = 0, is_dropframe: bool = False) -> Self:
        """
        :param hours: Hours, defaults to 0
        :param minutes: Minutes, defaults to 0
        :param seconds: Seconds, defaults to 0
        :param frames: Frames, defaults to 0
        :param is_dropframe: Current mode uses dropframes, defaults to False
        :return: Instance of TimeField with the data applied
        """
        raw = cls.STRUCT.pack(hours, minutes, seconds, frames, is_dropframe)
        return cls(raw)

    def uncreate(self) -> tuple:
        """Create arguments to feed into TimeField.create()"""
        return self.hours, self.minutes, self.seconds, self.frames, self.is_dropframe

    def total_seconds(self):
        """get the time as amount of seconds (excluding the frames)"""
        return self.seconds + (60 * self.minutes) + (60 * 60 * self.hours)

    def __repr__(self):
        return f"<time {self.hours} {self.minutes} {self.seconds} {self.frames}>"


class MixerEffectConfigField(FieldBase):
    """
    Data from the `_MeC` field. This stores basic info about the M/E units.

    The mixer will send multiple fields, one for each M/E unit.

    ====== ==== ====== ===========
    Offset Size Type   Description
    ====== ==== ====== ===========
    0      1    u8     M/E index
    1      1    u8     Number of keyers on this M/E
    2      2    ?      padding
    ====== ==== ====== ===========

    After parsing:

    :ivar index: M/E index
    :ivar keyers: Number of keyers on this M/E
    """

    CODE = "_MeC"
    STRUCT = struct.Struct('>BB2x')

    def __init__(self, raw: bytes):
        """
        :param raw: Bytes containing the field contents
        """
        self.raw = raw
        field = self.STRUCT.unpack(raw)
        self.index = field[0]
        self.keyers = field[1]

    @classmethod
    def create(cls, index: int, keyers: int) -> Self:
        """
        :param index: M/E index
        :param keyers: Number of keyers on this M/E
        :return: Instance of MixerEffectConfigField with the data applied
        """
        raw = cls.STRUCT.pack(index, keyers)
        return cls(raw)

    def uncreate(self) -> tuple:
        """Create arguments to feed into MixerEffectConfigField.create()"""
        return self.index, self.keyers

    def __repr__(self):
        return f"<mixer-effect-config index={self.index} keyers={self.keyers}>"


class VideoModeCapabilityField(FieldBase):
    """
    Data from the `_VMC` field. This describes all the video modes supported by the hardware and the associated multiview
    and downconvert modes.

    The first 2 bytes is the number of modes supported, then there's a 13 byte block that's repeated for every mode that has
    the mode number, the possible multiview modes in this mode and the possible downconvert modes.

    ====== ==== ====== ===========
    Offset Size Type   Description
    ====== ==== ====== ===========
    0      2    u16    Number of video modes
    ====== ==== ====== ===========

    Followed by this repeated block:

    ====== ==== ====== ===========
    Offset Size Type   Description
    ====== ==== ====== ===========
    0      1    u8     Video mode number referring to a VideoMode
    1      3    ?      padding
    4      4    u32    Multiview modes bitfield
    8      4    u32    Downscale modes bitfield
    12     1    bool   Requires reconfiguration
    ====== ==== ====== ===========

    After parsing:

    :ivar count: Number of video modes
    """

    CODE = "_VMC"
    STRUCT = struct.Struct('>H')
    REPEATED = struct.Struct('>B3x I I ?')

    def __init__(self, raw: bytes):
        """
        :param raw: Bytes containing the field contents
        """
        self.raw = raw
        field = self.STRUCT.unpack(raw)
        self.count = field[0]
        self.modes = []
        for i in range(self.count):
            rf = self.REPEATED.unpack_from(raw, self.STRUCT.size + (i * self.REPEATED.size))
            self.modes.append({
                "modenum": rf[0],
                "multiview": self._bitfield_to_modes(rf[1]),
                "downscale": self._bitfield_to_modes(rf[2]),
                "reconfig": rf[3],
                "mode": self._int_to_mode(rf[0]),
            })


    @classmethod
    def create(cls, count: int) -> Self:
        """
        :param count: Number of video modes
        :return: Instance of VideoModeCapabilityField with the data applied
        """
        raw = cls.STRUCT.pack(count)
        return cls(raw)

    def uncreate(self) -> tuple:
        """Create arguments to feed into VideoModeCapabilityField.create()"""
        return self.count,

    def _int_to_mode(self, mode: int):
        """The VideoMode corresponding with this mode"""
        return VideoModeField(VideoModeField.STRUCT.pack(mode))

    def _bitfield_to_modes(self, bitfield: int):
        """Convert a mode bitfield to a list of VideoModeField instances"""
        result = []
        for i in range(0, 32):
            if bitfield & (2 ** i):
                result.append(self._int_to_mode(i))
        return result

    def __repr__(self):
        return f"<video-mode-capability count={self.count}>"


class FirmwareVersionField(FieldBase):
    """
    Data from the `_ver` field. This stores the major/minor firmware version numbers

    ====== ==== ====== ===========
    Offset Size Type   Description
    ====== ==== ====== ===========
    0      2    u16    Major version
    2      2    u16    Minor version
    ====== ==== ====== ===========

    After parsing:

    :ivar major: Major version
    :ivar minor: Minor version
    :ivar version: Human readable version string
    """

    CODE = "_ver"
    STRUCT = struct.Struct('>HH')

    def __init__(self, raw: bytes):
        """
        :param raw: Bytes containing the field contents
        """
        self.raw = raw
        field = self.STRUCT.unpack(raw)
        self.major = field[0]
        self.minor = field[1]

        self.version = f"{self.major}.{self.minor}"

    @classmethod
    def create(cls, major: int, minor: int) -> Self:
        """
        :param major: Major version
        :param minor: Minor version
        :return: Instance of FirmwareVersionField with the data applied
        """
        raw = cls.STRUCT.pack(major, minor)
        return cls(raw)

    def uncreate(self) -> tuple:
        """Create arguments to feed into FirmwareVersionField.create()"""
        return self.major, self.minor

    def __repr__(self):
        return f"<firmware-version {self.version}>"


class ProductNameField(FieldBase):
    """
    Data from the `_pin` field. This stores the product name and model for this switcher

    ====== ==== ====== ===========
    Offset Size Type   Description
    ====== ==== ====== ===========
    0      40   string Product name
    40     4    u32    Model code
    ====== ==== ====== ===========

    After parsing:

    :ivar name: Product name
    :ivar model: Model code
    """

    CODE = "_pin"
    STRUCT = struct.Struct('>40s I')

    def __init__(self, raw: bytes):
        """
        :param raw: Bytes containing the field contents
        """
        self.raw = raw
        field = self.STRUCT.unpack(raw)
        self.name = self._get_string(field[0])
        self.model = field[1]

    @classmethod
    def create(cls, name: str, model: int = 0) -> Self:
        """
        :param name: Product name
        :param model: Model code, defaults to 0
        :return: Instance of ProductNameField with the data applied
        """
        raw = cls.STRUCT.pack(name, model)
        return cls(raw)

    def uncreate(self) -> tuple:
        """Create arguments to feed into ProductNameField.create()"""
        return self.name, self.model

    def __repr__(self):
        return f"<product-name {self.name} model={self.model}>"


class InputPropertiesField(FieldBase):
    """
    Data from the `InPr` field. This stores information about all the internal and external inputs.

    The mixer will send multiple fields, one for each input

    ====== ==== ====== ===========
    Offset Size Type   Description
    ====== ==== ====== ===========
    0      2    u16    Source index
    2      20   string Long name
    22     4    string Short name for button
    26     1    bool   Name is unchanged from factory naming
    27     1    ?      Unknown
    28     2    u16    WHEE
    30     2    u16    WHEEE
    32     2    u16    WHEOOO
    34     1    u8     describes routing options for this port
    35     1    u8     describes routing options for this port
    ====== ==== ====== ===========

    After parsing:

    :ivar index: Source index
    :ivar name: Long name
    :ivar short_name: Short name for button
    :ivar default_name: Name is unchanged from factory naming
    :ivar source_ports: WHEE
    :ivar external_port_type: WHEEE
    :ivar port_type: WHEOOO
    :ivar bitfield_availability: describes routing options for this port
    :ivar bitfield_availability2: describes routing options for this port
    """

    CODE = "InPr"
    STRUCT = struct.Struct('>H20s4s?x HH HBB')

    def __init__(self, raw: bytes):
        """
        :param raw: Bytes containing the field contents
        """
        self.raw = raw
        field = self.STRUCT.unpack(raw)
        self.index = field[0]
        self.name = self._get_string(field[1])
        self.short_name = self._get_string(field[2])
        self.default_name = field[3]
        self.source_ports = field[4]
        self.external_port_type = field[5]
        self.port_type = field[6]
        self.available_aux = field[7] & (1 << 0) != 0
        self.available_multiview = field[7] & (1 << 1) != 0
        self.available_supersource_art = field[7] & (1 << 2) != 0
        self.available_supersource_box = field[7] & (1 << 3) != 0
        self.available_key_source = field[7] & (1 << 4) != 0
        self.available_aux1 = field[7] & (1 << 5) != 0
        self.available_aux2 = field[7] & (1 << 6) != 0
        self.available_usb = field[7] & (1 << 7) != 0
        self.available_me1 = field[8] & (1 << 0) != 0
        self.available_m2 = field[8] & (1 << 1) != 0

    @classmethod
    def create(cls, index: int, name: str, short_name: str, default_name: bool, source_ports: int, external_port_type: int, port_type: int, bitfield_availability: int, bitfield_availability2: int) -> Self:
        """
        :param index: Source index
        :param name: Long name
        :param short_name: Short name for button
        :param default_name: Name is unchanged from factory naming
        :param source_ports: WHEE
        :param external_port_type: WHEEE
        :param port_type: WHEOOO
        :param bitfield_availability: describes routing options for this port
        :param bitfield_availability2: describes routing options for this port
        :return: Instance of InputPropertiesField with the data applied
        """
        raw = cls.STRUCT.pack(index, name, short_name, default_name, source_ports, external_port_type, port_type,
            bitfield_availability, bitfield_availability2)
        return cls(raw)

    def uncreate(self) -> tuple:
        """Create arguments to feed into InputPropertiesField.create()"""
        return self.index, self.name, self.short_name, self.default_name, self.source_ports, self.external_port_type, self.port_type, self.bitfield_availability, self.bitfield_availability2

    def __repr__(self):
        return f"<input-properties index={self.index} name={self.name} short_name={self.short_name}>"


class VideoModeField(FieldBase):
    """
    Data from the `VidM` field. This sets the video standard the switcher operates on internally.

    ====== ==== ====== ===========
    Offset Size Type   Description
    ====== ==== ====== ===========
    0      1    u8     Video mode
    1      3    ?      Padding
    ====== ==== ====== ===========

    The `Video mode` is an enum of these values:

    === ==========
    Key Video mode
    === ==========
    0   NTSC (525i59.94)
    1   PAL (625i50)
    2   NTSC widescreen (525i59.94)
    3   PAL widescreen (625i50)
    4   720p50
    5   720p59.94
    6   1080i50
    7   1080i59.94
    8   1080p23.98
    9   1080p24
    10  1080p25
    11  1080p29.97
    12  1080p50
    13  1080p59.94
    14  4k23.98
    15  4k24
    16  4k25
    17  4k29.97
    18  4k50
    19  4k59.94
    20  8k23.98
    21  8k24
    22  8k25
    23  8k29.97
    24  8k50
    25  8k59.94
    26  1080p30
    27  1080p60
    28  720p60
    29  1080i60
    === ==========

    After parsing:

    :ivar mode: Video mode
    :ivar resolution: vertical resolution of the mode
    :ivar interlaced: the current mode is interlaced
    :ivar rate: the refresh rate of the mode
    :ivar widescreen: this is not a 4:3 resolution
    """

    CODE = "VidM"
    STRUCT = struct.Struct('>B3x')

    def __init__(self, raw: bytes):
        """
        :param raw: Bytes containing the field contents
        """
        self.raw = raw
        field = self.STRUCT.unpack(raw)
        self.mode = field[0]

        lut_mode = {
                0: (True, 59.94, 525, False),
                1: (True, 50, 625, False),
                2: (True, 59.94, 525, True),
                3: (True, 50, 625, True),
                4: (False, 50, 720, True),
                5: (False, 59.94, 720, True),
                6: (True, 50, 1080, True),
                7: (True, 59.94, 1080, True),
                8: (False, 23.98, 1080, True),
                9: (False, 24, 1080, True),
                10: (False, 25, 1080, True),
                11: (False, 29.97, 1080, True),
                12: (False, 50, 1080, True),
                13: (False, 59.94, 1080, True),
                14: (False, 23.98, 2160, True),
                15: (False, 24, 2160, True),
                16: (False, 25, 2160, True),
                17: (False, 29.97, 2160, True),
                18: (False, 50, 2160, True),
                19: (False, 59.94, 2160, True),
                20: (False, 23.98, 4320, True),
                21: (False, 24, 4320, True),
                22: (False, 25, 4320, True),
                23: (False, 29.97, 4320, True),
                24: (False, 50, 4320, True),
                25: (False, 59.94, 4320, True),
                26: (False, 30, 1080, True),
                27: (False, 60, 1080, True),
                28: (False, 60, 720, True),
                29: (True, 60, 1080, True)
        }
        self.resolution = lut_mode[self.mode][2]
        self.interlaced = lut_mode[self.mode][0]
        self.rate = lut_mode[self.mode][1]
        self.widescreen = lut_mode[self.mode][3]

    @classmethod
    def create(cls, mode: int) -> Self:
        """
        :param mode: Video mode
        :return: Instance of VideoModeField with the data applied
        """
        raw = cls.STRUCT.pack(mode)
        return cls(raw)

    def uncreate(self) -> tuple:
        """Create arguments to feed into VideoModeField.create()"""
        return self.mode,

    def get_resolution(self):
        """get the resolution as a (width, height) tuple"""
        lut = {
         525: [720, 480], 625: [720, 576], 720: [1280, 720], 1080: [1920, 1080], 2160: [3840, 2160], 4320: [7680, 4320]
        }
        return lut[self.resolution]

    def get_pixels(self):
        """get the total number of pixels in a single frame"""
        width, height = self.get_resolution()
        return width * height

    def get_label(self):
        """get a text description of the current mode"""
        if self.resolution is None:
            return f'unknown [{self.mode}]'

        pi = 'p'
        if self.interlaced:
            pi = 'i'
        aspect = ''
        if self.resolution < 720:
            if self.widescreen:
                aspect = ' 16:9'
            else:
                aspect = ' 4:3'
        return f'{self.resolution}{pi}{self.rate}{aspect}'

    def __repr__(self):
        return f"<video-mode {self.get_label()}>"


class MediaplayerSelectedField(FieldBase):
    """
    Data from the `MPCE` field. This defines what media from the media pool is loaded in a specific media player. There is
    one MPCE field per mediaplayer in the hardware.

    ====== ==== ====== ===========
    Offset Size Type   Description
    ====== ==== ====== ===========
    0      1    u8     Mediaplayer index
    1      1    u8     Source type
    2      1    u8     Source index loaded in the mediaplayer
    3      1    ?      padding
    ====== ==== ====== ===========

    After parsing:

    :ivar index: Mediaplayer index
    :ivar source_type: Source type
    :ivar slot: Source index loaded in the mediaplayer
    """

    CODE = "MPCE"
    STRUCT = struct.Struct('>BBBx')

    def __init__(self, raw: bytes):
        """
        :param raw: Bytes containing the field contents
        """
        self.raw = raw
        field = self.STRUCT.unpack(raw)
        self.index = field[0]
        self.source_type = field[1]
        self.slot = field[2]

    @classmethod
    def create(cls, index: int, source_type: int, slot: int) -> Self:
        """
        :param index: Mediaplayer index
        :param source_type: Source type
        :param slot: Source index loaded in the mediaplayer
        :return: Instance of MediaplayerSelectedField with the data applied
        """
        raw = cls.STRUCT.pack(index, source_type, slot)
        return cls(raw)

    def uncreate(self) -> tuple:
        """Create arguments to feed into MediaplayerSelectedField.create()"""
        return self.index, self.source_type, self.slot

    def __repr__(self):
        return f"<mediaplayer-selected index={self.index} source_type={self.source_type} slot={self.slot}>"


