# Generated by generate.py
from unittest import TestCase


from .fields import TopologyField

class TestTopologyField(TestCase):
    def test_mini_extreme(self):
        raw = b'\x01\x1d\x02\x03\x00\x02\x01\x00\n\x01\x00\x01\x00\x00\x00\x01\x00\x00\x01\x00\x00\x00\x01\x01\x01\x00\x00\x00'
        field = TopologyField(raw)
        self.assertEqual(1, field.me_units, msg="TopologyField.me_units")
        self.assertEqual(29, field.sources, msg="TopologyField.sources")
        self.assertEqual(2, field.mediaplayers, msg="TopologyField.mediaplayers")
        self.assertEqual(10, field.hyperdecks, msg="TopologyField.hyperdecks")
        self.assertEqual(2, field.downstream_keyers, msg="TopologyField.downstream_keyers")
        self.assertEqual(3, field.aux_busses, msg="TopologyField.aux_busses")
        self.assertEqual(1, field.dve, msg="TopologyField.dve")
        self.assertEqual(0, field.mixminus_outputs, msg="TopologyField.mixminus_outputs")
        self.assertEqual(1, field.multiviewers, msg="TopologyField.multiviewers")
        self.assertEqual(False, field.multiviewer_routable, msg="TopologyField.multiviewer_routable")
        self.assertEqual(True, field.camera_control, msg="TopologyField.camera_control")
        self.assertEqual(True, field.advanced_chroma_keyers, msg="TopologyField.advanced_chroma_keyers")
        self.assertEqual(0, field.stingers, msg="TopologyField.stingers")
        self.assertEqual(1, field.supersources, msg="TopologyField.supersources")
        self.assertEqual(0, field.rs485, msg="TopologyField.rs485")
        self.assertEqual(True, field.only_configurable_outputs, msg="TopologyField.only_configurable_outputs")

    def test_production_studio_4k(self):
        raw = b'\x01\x18\x02\x01\x00\x02\x01\x00\x04\x00\x00\x00\x01\x00\x00\x00\x00\x01\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00'
        field = TopologyField(raw)
        self.assertEqual(1, field.me_units, msg="TopologyField.me_units")
        self.assertEqual(24, field.sources, msg="TopologyField.sources")
        self.assertEqual(2, field.mediaplayers, msg="TopologyField.mediaplayers")
        self.assertEqual(4, field.hyperdecks, msg="TopologyField.hyperdecks")
        self.assertEqual(2, field.downstream_keyers, msg="TopologyField.downstream_keyers")
        self.assertEqual(1, field.aux_busses, msg="TopologyField.aux_busses")
        self.assertEqual(0, field.dve, msg="TopologyField.dve")
        self.assertEqual(0, field.mixminus_outputs, msg="TopologyField.mixminus_outputs")
        self.assertEqual(1, field.multiviewers, msg="TopologyField.multiviewers")
        self.assertEqual(True, field.multiviewer_routable, msg="TopologyField.multiviewer_routable")
        self.assertEqual(True, field.camera_control, msg="TopologyField.camera_control")
        self.assertEqual(False, field.advanced_chroma_keyers, msg="TopologyField.advanced_chroma_keyers")
        self.assertEqual(0, field.stingers, msg="TopologyField.stingers")
        self.assertEqual(0, field.supersources, msg="TopologyField.supersources")
        self.assertEqual(0, field.rs485, msg="TopologyField.rs485")
        self.assertEqual(False, field.only_configurable_outputs, msg="TopologyField.only_configurable_outputs")

    def test_television_studio_hd(self):
        raw = b'\x01\x18\x02\x01\x04\x02\x01\x01\x04\x01\x00\x00\x01\x01\x04\x00\x00\x00\x01\x01\x01\x01\x00\x00\x00\x10\x00\x06'
        field = TopologyField(raw)
        self.assertEqual(1, field.me_units, msg="TopologyField.me_units")
        self.assertEqual(24, field.sources, msg="TopologyField.sources")
        self.assertEqual(2, field.mediaplayers, msg="TopologyField.mediaplayers")
        self.assertEqual(4, field.hyperdecks, msg="TopologyField.hyperdecks")
        self.assertEqual(2, field.downstream_keyers, msg="TopologyField.downstream_keyers")
        self.assertEqual(1, field.aux_busses, msg="TopologyField.aux_busses")
        self.assertEqual(1, field.dve, msg="TopologyField.dve")
        self.assertEqual(4, field.mixminus_outputs, msg="TopologyField.mixminus_outputs")
        self.assertEqual(1, field.multiviewers, msg="TopologyField.multiviewers")
        self.assertEqual(True, field.multiviewer_routable, msg="TopologyField.multiviewer_routable")
        self.assertEqual(True, field.camera_control, msg="TopologyField.camera_control")
        self.assertEqual(False, field.advanced_chroma_keyers, msg="TopologyField.advanced_chroma_keyers")
        self.assertEqual(0, field.stingers, msg="TopologyField.stingers")
        self.assertEqual(0, field.supersources, msg="TopologyField.supersources")
        self.assertEqual(1, field.rs485, msg="TopologyField.rs485")
        self.assertEqual(False, field.only_configurable_outputs, msg="TopologyField.only_configurable_outputs")


from .fields import FairlightSoloField

class TestFairlightSoloField(TestCase):
    def test_aminiextreme1(self):
        raw = b'\x01\x15\xe8\x90\xff\xff\xfd\xa8\x05\x16\xff\xff\xff\xff\x01\x00\xff\xff\xff\xff\xff\xff\x01\x00'
        field = FairlightSoloField(raw)
        self.assertEqual('1302.0', field.strip_id, msg="FairlightSoloField.strip_id")
        self.assertEqual(True, field.solo, msg="FairlightSoloField.solo")
        self.assertEqual(1302, field.channel, msg="FairlightSoloField.channel")
        self.assertEqual(0, field.subchannel, msg="FairlightSoloField.subchannel")
        self.assertEqual(1, field.is_split_lr, msg="FairlightSoloField.is_split_lr")


from .fields import FairlightHeadphonesField

class TestFairlightHeadphonesField(TestCase):
    def test_aminiextreme1(self):
        raw = b'\x00\x00\x00<\xff\xff\xfd\xa8\x00\x00\xff\xff\xff\xff\xe8\x90\x00lSr\xff\xff\xe8\x90\x00\x00\x01\x00\xff\xff\xe8\x90'
        field = FairlightHeadphonesField(raw)
        self.assertEqual(False, field.unmuted, msg="FairlightHeadphonesField.unmuted")
        self.assertEqual(60, field.volume, msg="FairlightHeadphonesField.volume")


from .fields import FairlightTallyField

class TestFairlightTallyField(TestCase):
    def test_input1(self):
        raw = b'\x00\n\xc3\x00\x0b\xcc\x00\x0b\xff\xff\xff\xff\xff\xff\x01\x00\x00\x01\x01\xff\xff\xff\xff\xff\xff\x01\x00\x00\x02\x00\xff\xff\xff\xff\xff\xff\x01\x00\x00\x03\x00\xff\xff\xff\xff\xff\xff\x01\x00\x00\x04\x00\xff\xff\xff\xff\xff\xff\x01\x00\x00\x05\x00\xff\xff\xff\xff\xff\xff\x01\x00\x00\x06\x00\xff\xff\xff\xff\xff\xff\x01\x00\x00\x07\x00\xff\xff\xff\xff\xff\xff\x01\x00\x00\x08\x00\xff\xff\xff\xff\xff\xff\x01\x00\x05\x15\x00\xff\xff\xff\xff\xff\xff\x01\x00\x05\x16\x00\x01\x00'
        field = FairlightTallyField(raw)
        self.assertEqual(10, field.num, msg="FairlightTallyField.num")
        self.assertEqual({'1.0': True, '2.0': False, '3.0': False, '4.0': False, '5.0': False, '6.0': False, '7.0': False, '8.0': False, '1301.0': False, '1302.0': False}, field.tally, msg="FairlightTallyField.tally")

    def test_mic1(self):
        raw = b'\x00\n\xc3\x00\x0b\xcc\x00\x0b\xff\xff\xff\xff\xff\xff\x01\x00\x00\x01\x00\xff\xff\xff\xff\xff\xff\x01\x00\x00\x02\x00\xff\xff\xff\xff\xff\xff\x01\x00\x00\x03\x00\xff\xff\xff\xff\xff\xff\x01\x00\x00\x04\x00\xff\xff\xff\xff\xff\xff\x01\x00\x00\x05\x00\xff\xff\xff\xff\xff\xff\x01\x00\x00\x06\x00\xff\xff\xff\xff\xff\xff\x01\x00\x00\x07\x00\xff\xff\xff\xff\xff\xff\x01\x00\x00\x08\x00\xff\xff\xff\xff\xff\xff\x01\x00\x05\x15\x01\xff\xff\xff\xff\xff\xff\x01\x00\x05\x16\x00\x01\x00'
        field = FairlightTallyField(raw)
        self.assertEqual(10, field.num, msg="FairlightTallyField.num")
        self.assertEqual({'1.0': False, '2.0': False, '3.0': False, '4.0': False, '5.0': False, '6.0': False, '7.0': False, '8.0': False, '1301.0': True, '1302.0': False}, field.tally, msg="FairlightTallyField.tally")


from .fields import InputPropertiesField

class TestInputPropertiesField(TestCase):
    def test_me_black(self):
        raw = b'\x00\x00Black\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00BLK\x00\x01\x00\x01\x00\x01\x00\x01\x00\xff\x01'
        field = InputPropertiesField(raw)
        self.assertEqual(0, field.index, msg="InputPropertiesField.index")
        self.assertEqual('Black', field.name, msg="InputPropertiesField.name")
        self.assertEqual('BLK', field.short_name, msg="InputPropertiesField.short_name")
        self.assertEqual(256, field.port_type, msg="InputPropertiesField.port_type")
        self.assertEqual(256, field.external_port_type, msg="InputPropertiesField.external_port_type")
        self.assertEqual(256, field.source_ports, msg="InputPropertiesField.source_ports")


from .fields import VideoModeField

class TestVideoModeField(TestCase):
    def test_mini_1080p60(self):
        raw = b'\x1b\x00\x00\x00'
        field = VideoModeField(raw)
        self.assertEqual(27, field.mode, msg="VideoModeField.mode")
        self.assertEqual(60, field.rate, msg="VideoModeField.rate")
        self.assertEqual(1080, field.resolution, msg="VideoModeField.resolution")
        self.assertEqual(False, field.interlaced, msg="VideoModeField.interlaced")
        self.assertEqual(True, field.widescreen, msg="VideoModeField.widescreen")
        self.assertEqual([1920, 1080], field.get_resolution(), msg="VideoModeField.get_resolution()")
        self.assertEqual(2073600, field.get_pixels(), msg="VideoModeField.get_pixels()")
        self.assertEqual('1080p60', field.get_label(), msg="VideoModeField.get_label()")


